months = ['Январь',
          'Февраль',
          'Март',
          'Апрель',
          'Май',
          'Июнь',
          'Июль',
          'Август',
          'Сентябрь',
          'Октябрь',
          'Ноябрь',
          'Декабрь']

subjects = [{
    'name': 'математика',
    'min_score': 39,
    'a_questions_start_col': 10,
    'a_questions_end_col': 24,
    'b_questions_start_col': 25,
    'b_questions_end_col': 29,
    'test_date_col': 7,
    'question_complete_mark': 5.0,
    'custom_a_table': {0: 0,
                       1: 9,
                       2: 17,
                       3: 25,
                       4: 32,
                       5: 39,
                       6: 44,
                       7: 48,
                       8: 51,
                       9: 53,
                       10: 55,
                       11: 57,
                       12: 59,
                       13: 61,
                       14: 63,
                       15: 65},
    'custom_b_table': {0: 0,
                       1: 11,
                       2: 19,
                       3: 25,
                       4: 30,
                       5: 35}
},
    {
        'name': 'физика',
        'min_score': 39,
        'question_complete_mark': 5.0,
    },
    {
        'name': 'русский язык',
        'min_score': 40,
        'a_questions_start_col': 10,
        'a_questions_end_col': 26,
        'b_questions_start_col': 27,
        'b_questions_end_col': 34,
        'test_date_col': 7,
        'question_complete_mark': 0.4,
        'custom_a_table': {0: 0,
                           1: 10,
                           2: 19,
                           3: 27,
                           4: 34,
                           5: 38,
                           6: 41,
                           7: 43,
                           8: 45,
                           9: 47,
                           10: 49,
                           11: 51,
                           12: 53,
                           13: 55,
                           14: 57,
                           15: 58,
                           16: 59,
                           17: 60},
        'custom_b_table': {0: 0,
                           1: 10,
                           2: 19,
                           3: 28,
                           4: 35,
                           5: 37,
                           6: 38,
                           7: 39,
                           8: 40}
    }]
